---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections:
  _volunteering:
    default_front_matter_template: volunteering
  _learning:
    default_front_matter_template: learning
  _nurseries:
    default_front_matter_template: nurseries
  _young-people:
    default_front_matter_template: young-people
  _activities:
    default_front_matter_template: activities
  _sections:
    default_front_matter_template: sections
  _jobs:
    default_front_matter_template: jobs
  _stories:
    default_front_matter_template: stories
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
