---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - pages
- type: directory
  path: _volunteering
  label: Volunteering
  create: documents
  match: "**/*"
  templates:
  - volunteering
- type: directory
  path: _jobs
  label: Jobs
  create: documents
  match: "**/*"
  templates:
  - jobs
- type: directory
  path: _stories
  label: Stories
  create: documents
  match: "**/*"
  templates:
  - stories
- type: directory
  path: _young-people
  label: Young people
  create: documents
  match: "**/*"
  templates:
  - young-people
- type: directory
  path: _learning
  label: Learning
  create: documents
  match: "**/*"
  templates:
  - learning
- type: directory
  path: _nurseries
  label: Nurseries
  create: documents
  match: "**/*"
  templates:
  - nurseries
- type: directory
  path: _activities
  label: Activities
  create: documents
  match: "**/*"
  templates:
  - activities
- type: directory
  path: _sections
  label: Sections
  create: documents
  match: "**/*"
  templates:
  - sections
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
