---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _volunteering
  label: Volunteering
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _jobs
  label: Jobs
  create: all
  match: "**/*"
- type: directory
  path: _stories
  label: Stories
  create: all
  match: "**/*"
- type: directory
  path: _young-people
  label: Young-people
  create: all
  match: "**/*"
- type: directory
  path: _learning
  label: Learning
  create: all
  match: "**/*"
- type: directory
  path: _nurseries
  label: Nurseries
  create: all
  match: "**/*"
- type: directory
  path: _activities
  label: Activities
  create: all
  match: "**/*"
- type: directory
  path: _sections
  label: Sections
  create: all
  match: "**/*"
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
